# SkyChatFilter - Config

# localized messages
Language:
  German:
    AntiSpamTriggered: "&cDu kannst nicht so viele Nachrichten in so kurzer Zeit senden!"
    TextTooSimilar: "&cDu kannst nicht dieselbe Nachricht nochmal senden!"
    NoAdvertising: "&cEs ist dir nicht erlaubt andere Server oder Webseiten zu erwähnen!"
    ActionAlreadyPerformed: "&cEs wurde für diese Nachricht bereits eine Aktion ausgeführt!"
    NoSwearing: "&cDie Benutzung von Schimpfwörtern sowie die Umgehung des Filters ist verboten!"
  English:
    AntiSpamTriggered: "&cYou cannot send that many messages in such a short time!"
    TextTooSimilar: "&cYou cannot send the same message twice!"
    NoAdvertising: "&cYou are not allowed to mention other servers or websites!"
    ActionAlreadyPerformed: "&cAn action for this message has already been performed!"
    NoSwearing: "&cSwearing and circumventing the filter is prohibited!"
  Servers:
    Default: German
    SkyBlockUS: English
    LobbyUS: English

# AntiSpam
FloodClearPeriodInSeconds: 4
FloodMaxMessagesPerPeriodAfterJoin: 3
FloodMaxMessagesPerPeriodWithoutJoin: 6
FloodTimeUntilNoMoreJoinInSeconds: 30
FloodKickAfterXOverMax: 10
SameMessageSimilarity: 0.8
SameMessageMinLength: 11
SameMessageExpiryInSeconds: 30
SameMessageSaveAmount: 5

# AntiAdvertising
BlacklistRegEx:
- '(http(s)?:\/\/.)?(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}( ?\. ?| ?\(?dot\)? ?)[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)'
- '(?:[0-9]{1,3}( ?\. ?|\(?dot\)?)){3}[0-9]{1,3}'
- 'skyparty|hypixel|gomme|skycave'
- '([^\w\d]|_|dot|punkt)(eu|net|com|org|tk|ch|at|ca|io|de|ck|au|ru|cn\.in|co\.uk|co\.jp|fr|com\.br)((?!\S)|\/|:)'
- '([^\w\d ]|_|dot|punkt|\.[^\w\d])(me|us|gg|co)((?!\S)|\/|:)'
OverridingWhitelistRegEx:
- 'mrgames\.eu|mrsgames\.eu|mrvote\.eu|mrmc\.eu|google\..+'
AdStaffAlerter:
  AlertMessage: "&7[Werbung] &c{0}: {1} &3"
  Punishments:
    "[WerbBanP]": "ban {0} Werbung"
    "[WerbMute1h]": "mute {0} 1h Werbung"
    "[UnerwBanP]": "ban {0} Unerwünschter Spieler"
    "[OK]": "<allow>"